# https://taskfile.dev

version: '3'

tasks:
  install:
    cmd: poetry install --with dev

  code:check:
    desc: Check whether code formatting rules apply.
    cmds:
      - poetry run ruff format --check
      - poetry run ruff check

  code:
    desc: Format and standardise code.
    cmds:
      - poetry run ruff format
      - poetry run ruff --fix

  test:
    desc: Run Python tests.
    cmds:
      - poetry run python -m pytest

  build:app:
    cmd: poetry run pyinstaller main.spec -y

  build:dmg:
    cmd: ./builddmg.sh

  build:
    cmds:
      - task: build:app
      - task: build:dmg